import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Brain, TrendingUp, Zap } from "lucide-react";
import heroImage from "@assets/generated_images/athlete_sunrise_motivation_image.png";

export default function Home() {
  //todo: remove mock functionality - replace with actual user name
  const athleteName = "Alex";
  
  //todo: remove mock functionality - replace with actual recent routines
  const recentRoutines = [
    { id: "1", date: "Nov 20, 2025", opponent: "Carlos Vega" },
    { id: "2", date: "Nov 18, 2025", opponent: "Sarah Chen" },
  ];

  return (
    <div className="min-h-screen">
      <section 
        className="relative h-[60vh] flex items-center justify-center bg-gradient-to-b from-primary/20 to-background"
        style={{
          backgroundImage: `linear-gradient(to bottom, rgba(0,0,0,0.6), rgba(0,0,0,0.8)), url(${heroImage})`,
          backgroundSize: 'cover',
          backgroundPosition: 'center',
        }}
      >
        <div className="text-center space-y-6 px-4">
          <h1 className="font-display font-bold text-4xl md:text-6xl text-white">
            Welcome back, {athleteName}
          </h1>
          <p className="text-xl md:text-2xl text-white/90 max-w-2xl mx-auto">
            Ready to enter your optimal mental state?
          </p>
          <Link href="/setup">
            <Button 
              size="lg" 
              className="h-14 px-8 text-lg gap-2"
              data-testid="button-start-routine"
            >
              <Zap className="h-5 w-5" />
              Start Pre-Match Routine
            </Button>
          </Link>
        </div>
      </section>

      <section className="container mx-auto px-4 py-12 max-w-6xl">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-12">
          <Card>
            <CardHeader>
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-primary/10">
                  <Brain className="h-6 w-6 text-primary" />
                </div>
                <CardTitle>AI-Powered</CardTitle>
              </div>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground">
                Personalized routines generated by advanced AI based on your profile and match conditions
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-primary/10">
                  <TrendingUp className="h-6 w-6 text-primary" />
                </div>
                <CardTitle>Track Progress</CardTitle>
              </div>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground">
                Review your routine history and see how preparation impacts performance
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-primary/10">
                  <Zap className="h-6 w-6 text-primary" />
                </div>
                <CardTitle>10 Minutes</CardTitle>
              </div>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground">
                Quick, effective mental activation combining breathing, strategy, and motivation
              </p>
            </CardContent>
          </Card>
        </div>

        {recentRoutines.length > 0 && (
          <div>
            <h2 className="font-display font-semibold text-2xl mb-6">Recent Routines</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {recentRoutines.map((routine) => (
                <Link key={routine.id} href={`/routine/${routine.id}`}>
                  <Card className="hover-elevate transition-all cursor-pointer" data-testid={`card-routine-${routine.id}`}>
                    <CardHeader>
                      <CardTitle className="text-lg">{routine.date}</CardTitle>
                    </CardHeader>
                    <CardContent>
                      <p className="text-muted-foreground">vs {routine.opponent}</p>
                    </CardContent>
                  </Card>
                </Link>
              ))}
            </div>
          </div>
        )}
      </section>
    </div>
  );
}
